name: Gerar Pac‑Man Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"        # roda uma vez por dia
  workflow_dispatch:           # permite execução manual

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gerar Pac‑Man contribution graph
        uses: abozanona/[email protected]
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Deploy SVG no branch output
        uses: crazy-max/[email protected]
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
